dist: trusty
sudo: false
language: php

services:
  - redis-server

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install: travis_retry composer update --prefer-dist

script:
  - ./vendor/bin/phpunit -v

cache:
  directories:
    - $HOME/.composer/cache
